from pathlib import Path

# ============================================
# 常量定义
# ============================================

# HTTP状态码
HTTP_200_OK = 200
HTTP_201_CREATED = 201
HTTP_204_NO_CONTENT = 204
HTTP_400_BAD_REQUEST = 400
HTTP_401_UNAUTHORIZED = 401
HTTP_403_FORBIDDEN = 403
HTTP_404_NOT_FOUND = 404
HTTP_409_CONFLICT = 409
HTTP_422_UNPROCESSABLE_ENTITY = 422
HTTP_500_INTERNAL_SERVER_ERROR = 500
HTTP_502_BAD_GATEWAY = 502
HTTP_503_SERVICE_UNAVAILABLE = 503

# 用户角色
ROLE_ADMIN = "admin"
ROLE_USER = "user"
ROLE_VIEWER = "viewer"

# 项目成员角色
PROJECT_ROLE_ADMIN = "admin"
PROJECT_ROLE_MEMBER = "member"
PROJECT_ROLE_VIEWER = "viewer"

# 执行状态
EXECUTION_STATUS_PENDING = "pending"
EXECUTION_STATUS_RUNNING = "running"
EXECUTION_STATUS_FINISHED = "finished"
EXECUTION_STATUS_FAILED = "failed"
EXECUTION_STATUS_CANCELLED = "cancelled"

# 触发类型
TRIGGER_TYPE_MANUAL = "manual"
TRIGGER_TYPE_SCHEDULE = "schedule"
TRIGGER_TYPE_API = "api"

# HTTP请求方法
HTTP_METHOD_GET = "GET"
HTTP_METHOD_POST = "POST"
HTTP_METHOD_PUT = "PUT"
HTTP_METHOD_DELETE = "DELETE"
HTTP_METHOD_PATCH = "PATCH"
HTTP_METHOD_HEAD = "HEAD"
HTTP_METHOD_OPTIONS = "OPTIONS"

HTTP_METHODS = [
    HTTP_METHOD_GET,
    HTTP_METHOD_POST,
    HTTP_METHOD_PUT,
    HTTP_METHOD_DELETE,
    HTTP_METHOD_PATCH,
    HTTP_METHOD_HEAD,
    HTTP_METHOD_OPTIONS
]

# 断言类型
ASSERTION_TYPE_STATUS_CODE = "status_code"
ASSERTION_TYPE_RESPONSE_TIME = "response_time"
ASSERTION_TYPE_JSON_PATH = "json_path"
ASSERTION_TYPE_REGEX = "regex"
ASSERTION_TYPE_HEADER = "header"
ASSERTION_TYPE_BODY_CONTAINS = "body_contains"

ASSERTION_TYPES = [
    ASSERTION_TYPE_STATUS_CODE,
    ASSERTION_TYPE_RESPONSE_TIME,
    ASSERTION_TYPE_JSON_PATH,
    ASSERTION_TYPE_REGEX,
    ASSERTION_TYPE_HEADER,
    ASSERTION_TYPE_BODY_CONTAINS
]

# 比较运算符
COMPARE_EQUALS = "equals"
COMPARE_NOT_EQUALS = "not_equals"
COMPARE_CONTAINS = "contains"
COMPARE_NOT_CONTAINS = "not_contains"
COMPARE_GREATER_THAN = "greater_than"
COMPARE_LESS_THAN = "less_than"
COMPARE_GREATER_OR_EQUAL = "greater_or_equal"
COMPARE_LESS_OR_EQUAL = "less_or_equal"
COMPARE_REGEX_MATCH = "regex_match"

COMPARE_OPERATORS = [
    COMPARE_EQUALS,
    COMPARE_NOT_EQUALS,
    COMPARE_CONTAINS,
    COMPARE_NOT_CONTAINS,
    COMPARE_GREATER_THAN,
    COMPARE_LESS_THAN,
    COMPARE_GREATER_OR_EQUAL,
    COMPARE_LESS_OR_EQUAL,
    COMPARE_REGEX_MATCH
]

# 环境标识
ENV_DEVELOPMENT = "dev"
ENV_STAGING = "pre"
ENV_PRODUCTION = "prod"

# 存储类型
STORAGE_TYPE_LOCAL = "local"
STORAGE_TYPE_OSS = "oss"
STORAGE_TYPE_S3 = "s3"

# 定时任务频率
SCHEDULE_FREQUENCY_MINUTELY = "minutely"
SCHEDULE_FREQUENCY_HOURLY = "hourly"
SCHEDULE_FREQUENCY_DAILY = "daily"
SCHEDULE_FREQUENCY_WEEKLY = "weekly"
SCHEDULE_FREQUENCY_MONTHLY = "monthly"

# 默认分页
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100

# 默认超时时间（秒）
DEFAULT_TIMEOUT = 30
MAX_TIMEOUT = 600

# 任务优先级
TASK_PRIORITY_HIGH = 1
TASK_PRIORITY_NORMAL = 5
TASK_PRIORITY_LOW = 10

# 错误码
ERROR_CODE_SUCCESS = 0
ERROR_CODE_UNKNOWN = -1
ERROR_CODE_INVALID_PARAM = 1001
ERROR_CODE_UNAUTHORIZED = 1002
ERROR_CODE_FORBIDDEN = 1003
ERROR_CODE_NOT_FOUND = 1004
ERROR_CODE_CONFLICT = 1005
ERROR_CODE_INTERNAL_ERROR = 1006
ERROR_CODE_DATABASE_ERROR = 2001
ERROR_CODE_REDIS_ERROR = 2002
ERROR_CODE_CELERY_ERROR = 2003
ERROR_CODE_EXECUTION_ERROR = 3001
ERROR_CODE_REPORT_ERROR = 3002

# 项目路径
PROJECT_ROOT = Path(__file__).parent.parent
CONFIG_DIR = PROJECT_ROOT / "config"
CONFIG_FILE = CONFIG_DIR / "config.yaml"